---
- hosts: all
  gather_facts: no
  pre_tasks:
    - name: set ansible_host
      set_fact:
        ansible_host: "{{ foreman.ip }}"
      connection: local
    - name: run setup
      setup:
  tasks:
    - name: run ls
      command: ls
      register: ls_out

    - name: print ls output
      debug:
        var: ls_out.stdout




