---
- hosts: foreman_environment_production
  gather_facts: no
  pre_tasks:
  tasks:
    - name: run ls
      command: ls
      register: ls_out

    - name: print ls output
      debug:
        var: ls_out.stdout




