FROM debian:jessie

ARG ANSIBLE_VERSION

RUN set -x \
  && apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y \
             gcc \
             python-setuptools \
             python-crypto \
             ca-certificates \
  && easy_install pip \
  && if [ "${ANSIBLE_VERSION}" = "latest" ]; then pip install ansible; else pip install ansible\==${ANSIBLE_VERSION}; fi
