---
- include: "{{ ansible_os_family }}.yml"

- name: Geting shell results
  shell: "{{ item }}"
  register: geting_shell_results
  with_items: "{{ shhirose_motd_shell_results }}"
  when: shhirose_motd_shell_results | length > 0
  changed_when: False

- name: Edit motd
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ shhirose_motd_templates }}"
